# -*- coding: utf-8 -*-
"""Week3_Weather_Data_Analysis (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bdfcuyEZbNGnoLWJRF6svCfulaLtrue
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Python Project 1/GlobalWeatherRepository.csv")

print("Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)
print("\n Sample Output")
df.head()

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)

df['last_updated'] = pd.to_datetime(df['last_updated'])
df['Month'] = df['last_updated'].dt.month

def get_season(month):
    if month in [12,1,2]:
        return "Winter"
    elif month in [3,4,5]:
        return "Summer"
    elif month in [6,7,8]:
        return "Monsoon"
    else:
        return "Autumn"

df['Season'] = df['Month'].apply(get_season)

print("Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)
print("\n Sample Output")
df.head()

df['Date'] = df['last_updated'].dt.date
daily_temp = df.groupby('Date')['temperature_celsius'].mean()

plt.figure()

plt.plot(daily_temp.index, daily_temp.values)

plt.title("Daily Average Temperature Trend")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")

plt.show()

season_rain = df.groupby('Season')['precip_mm'].mean()

season_rain.plot(kind='bar')

plt.title("Average Rainfall by Season")
plt.xlabel("Season")
plt.ylabel("Rainfall (mm)")

plt.show()

plt.hist(df['temperature_celsius'], bins=20)

plt.title("Temperature Distribution")
plt.xlabel("Temperature")
plt.ylabel("Frequency")

plt.show()

plt.scatter(df['temperature_celsius'], df['humidity'])

plt.title("Temperature vs Humidity")
plt.xlabel("Temperature")
plt.ylabel("Humidity")

plt.show()

season_counts = df['Season'].value_counts()

plt.pie(season_counts, labels=season_counts.index, autopct='%1.1f%%')

plt.title("Season Distribution")

plt.show()